Repository alexjustesen/filament-spatie-laravel-activitylog, pull requests merged in 2022-05, with the labels that each got.

#17 Translate strings
  resources/lang/de/activity.php
  resources/lang/en/activity.php
  src/Resources/ActivityResource.php
Labels: 🎉 feature, 👍 good first issue

#14 [fix] ResourceFinder returns null if no resource
  src/ResourceFinder.php
Labels: 🐜 bug

#18 make pagination configurable
  config/filament-spatie-laravel-activitylog.php
  src/Resources/ActivityResource/Pages/ListActivities.php
Labels: 🎉 feature
